### ISSUE TITLE
Error making

### ISSUE THREAD

**Issue by kgleason** [cyclaero/void-zones-tools#1]
What versions of FreeBSD are supported? I'm currently trying to set this up inside a 10.3 jail (running on my FreeNAS), and I get the following:

    root@dns_1:/usr/local/src/void-zones-tools # make install clean CDEFS="-march=native"
    cc -march=native -std=c11 -g0 -Ofast -mssse3 -fstrict-aliasing -ffast-math -Wno-parentheses binutils.c -c -o binutils.o
    cc1: error: invalid option argument '-Ofast'
    cc1: error: unrecognized command line option "-std=c11"
    *** [binutils.o] Error code 1
    
    Stop in /usr/local/src/void-zones-tools.

Any suggestions?

**Comment by cyclaero** [comment]
Well, I developed this on FreeBSD 11, and that one got clang 3.8 on board. However, I used for all of my projects -Ofast and -std=c11 since FreeBSD 10.x. Perhaps GCC does not support this.

In the Makefile, either replace -Ofast with -O3 and remove -std=c11, or remove the question mark from the line:

`cc ?= clang`

**Comment by cyclaero** [comment]
no feedback -> closed.
